title:  Manjit Sehra
logo: "/images/Profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Results-driven data analyst, product owner and business system analyst with experiences and a track record of delivering innovative technical solutions that enhance the experience of both customers and analytic professionals. Proficient in SQL, Python, and Power BI, with a validated competence to automate dashboards, streamline processes, and provide tactical direction to stakeholders using easy-to-understand language. Skilled in analyzing behavioral data, identifying business gaps, and developing solutions that meet the needs of both internal and external stakeholders.
  <br> <br>
  <a href="https://www.linkedin.com/in/shuchangl/">View My LinkedIn Profile</a>
  <br>
  <a href="https://public.tableau.com/profile/shuchang.liang#!/">View My Tableau Work Samples</a>
  <br>
  <a href="hhttps://manjit-sehra.notion.site/Portfolio-Manjit-Sehra-2a1732d32ef44a5c96ac988f89994c17?pvs=4">View My Notion Portfolios</a>
theme: jekyll-theme-minimal   
  
 
